server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: shop-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/smartshop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 0123456789

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # Cấu hình Redis
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 311188236269-upt13pv1tadijt9f91ck9rgonnofbsbl.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:4200/auth/google/callback
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            resource-server:
              opaque-token:
                introspection-uri: "https://googleapis.com"
          facebook:
            client-id: 1117747529980605
            client-secret: 49617d581207fdcb221a2f3fea439e67
            redirect-uri: http://localhost:4200/auth/facebook/callback
            auth-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/v21.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
            scope:
              - email
              - public_profile

  ai:
    openai:
      api-key: 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
      base-url: https://integrate.api.nvidia.com/v1
      embedding:
        enabled: false
      chat:
        options:
          model: meta/llama-3.1-70b-instruct
          max-tokens: 2048

  mail:
    host: smtp.gmail.com
    port: 587
    username: thuandang021102@gmail.com
    password: 0123456789@T
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

cache:
  product:
    ttl: 300

jwt:
  signerKey: XcZY99Tw3J9fiSQYbZEIAi2JTfifpUolb2+/3AvVPveVK0or6PJ418iY71DvyUa1
  valid-duration: 1800
  refresh-duration: 36000

cloudinary:
  cloud-name: du6fyhjnk
  api-key: 729817939291514
  api-secret: KFXC17RTjhGrAtZWyXOEBhwqLaw

file:
  upload:
    user:
      avatar: ecommerce/users/avatars/
    product:
      thumbnail: ecommerce/products/thumbnails/
      gallery: ecommerce/products/galleries/
    review:
      image: ecommerce/reviews/images/
      video: ecommerce/reviews/videos/

paypal:
  client-id: AXspccyg2oC5Xr8-yRbHU_0x2QUVph8hk51I-zUW81ma8HvGtFc0REu-WE0P4WFpnZZmkH3z6XT3Fowh
  client-secret: ECSSSlU8ocuKfxBgDeVa5gBmPO92IfL0ElxA4HRn2GoWFXzbhf9E0Tpd8iECQWtcvpdFPrTrpr6z5oBG
  api:
    base-url: https://api-m.sandbox.paypal.com

